# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'servers.json')))

Vagrant.configure("2") do |config|
  servers.each do |server|

      config.vm.define server['name'] do |srv|
        srv.vm.hostname = server['name']
        srv.vm.box = server['box']
        srv.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        srv.vm.synced_folder "D:\\Development", "/development", type: "virtualbox"
        srv.vm.network "private_network", ip: server['ip']
        srv.vm.provision "shell", path: server['script'], privileged: true, args: server['ip']
        if server['ports']
          server['ports'].each do |port|
              srv.vm.network "forwarded_port", guest: port['guest'], host: port['host']
          end
        end
        srv.vm.provider "virtualbox" do |v|
            v.memory = server['ram']
            v.cpus = server['vcpu']
        end
      end
  end
end




