# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "docker-playground"
  config.vm.box = "ardole/centos7"
  config.vm.box_version = "0.1.0"
  config.ssh.username = "tux"
  config.vm.network "private_network",  ip: "192.168.50.10"
  config.vm.provision "shell", path: "install-docker.sh"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  #config.vm.synced_folder "C:\\Workspace", "/workspace", type: "virtualbox"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
