# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "debian"
  config.vm.box = "debian/stretch64"
  config.vm.network "private_network", ip: "192.168.50.11"
  config.vm.synced_folder "C:\\Workspace", "/workspace", type: "virtualbox"
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end
end



 
